apiVersion: v1
kind: Service
metadata:
  name: {{ include "movienight.fullname" . }}-{{ .Values.backend.name }}
  namespace: {{ include "movienight.namespace" . }}
  labels:
    {{- include "movienight.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  {{- if .Values.backend.service.sessionAffinity }}
  sessionAffinity: {{ .Values.backend.service.sessionAffinity }}
  sessionAffinityConfig:
    {{- toYaml .Values.backend.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "movienight.backend.selectorLabels" . | nindent 4 }}
