{{- if .Values.secrets.tmdbApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "movienight.fullname" . }}-secrets
  namespace: {{ include "movienight.namespace" . }}
  labels:
    {{- include "movienight.labels" . | nindent 4 }}
type: Opaque
data:
  tmdb-api-key: {{ .Values.secrets.tmdbApiKey | b64enc | quote }}
{{- end }}
