"""
HirePath – Job Database
Simulated jobs across 5 sources: LinkedIn, Indeed, Glassdoor, Monster, ZipRecruiter
"""

JOBS = [
    # ─── SOFTWARE ENGINEERING ───────────────────────────────────────────────
    {
        "id": 1, "title": "Senior Frontend Engineer", "company": "Stripe",
        "source": "LinkedIn", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$160K – $210K", "category": "Engineering",
        "description": "Build world-class payment UIs used by millions of developers.",
        "required_skills": ["react", "typescript", "javascript", "css", "html", "webpack"],
        "preferred_skills": ["next.js", "tailwind", "graphql", "a/b testing"],
        "experience_years_min": 5, "experience_years_max": 10,
        "education_required": "bachelor",
    },
    {
        "id": 2, "title": "Backend Software Engineer", "company": "Airbnb",
        "source": "Indeed", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$150K – $200K", "category": "Engineering",
        "description": "Scale distributed systems powering millions of nightly stays.",
        "required_skills": ["python", "java", "sql", "microservices", "rest", "kafka"],
        "preferred_skills": ["spark", "aws", "kubernetes", "docker"],
        "experience_years_min": 4, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 3, "title": "Full Stack Developer", "company": "Notion",
        "source": "Glassdoor", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$130K – $175K", "category": "Engineering",
        "description": "Build features across the entire stack for our productivity platform.",
        "required_skills": ["react", "node.js", "typescript", "postgresql", "graphql"],
        "preferred_skills": ["redis", "aws", "docker", "tailwind"],
        "experience_years_min": 3, "experience_years_max": 7,
        "education_required": "bachelor",
    },
    {
        "id": 4, "title": "Junior Software Developer", "company": "HubSpot",
        "source": "Monster", "location": "Boston, MA", "job_type": "Full-time",
        "salary_range": "$80K – $110K", "category": "Engineering",
        "description": "Develop customer-facing features for our CRM platform.",
        "required_skills": ["javascript", "python", "sql", "html", "css", "git"],
        "preferred_skills": ["react", "java", "agile"],
        "experience_years_min": 0, "experience_years_max": 2,
        "education_required": "bachelor",
    },
    {
        "id": 5, "title": "DevOps Engineer", "company": "Netflix",
        "source": "LinkedIn", "location": "Los Gatos, CA", "job_type": "Full-time",
        "salary_range": "$170K – $240K", "category": "Engineering",
        "description": "Maintain the infrastructure that streams to 200M+ users.",
        "required_skills": ["aws", "kubernetes", "docker", "terraform", "linux", "ci/cd"],
        "preferred_skills": ["ansible", "prometheus", "grafana", "python", "bash"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "bachelor",
    },
    {
        "id": 6, "title": "Cloud Solutions Architect", "company": "Salesforce",
        "source": "ZipRecruiter", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$180K – $250K", "category": "Engineering",
        "description": "Design cloud-native architectures for enterprise clients.",
        "required_skills": ["aws", "azure", "gcp", "kubernetes", "terraform", "microservices"],
        "preferred_skills": ["python", "java", "docker", "ci/cd"],
        "experience_years_min": 8, "experience_years_max": 15,
        "education_required": "bachelor",
    },
    {
        "id": 7, "title": "Site Reliability Engineer", "company": "Google",
        "source": "Glassdoor", "location": "Mountain View, CA", "job_type": "Full-time",
        "salary_range": "$185K – $260K", "category": "Engineering",
        "description": "Ensure reliability, scalability, and performance of Google's services.",
        "required_skills": ["linux", "python", "go", "kubernetes", "monitoring", "ci/cd"],
        "preferred_skills": ["prometheus", "grafana", "terraform", "bash"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "bachelor",
    },
    {
        "id": 8, "title": "iOS Mobile Developer", "company": "Lyft",
        "source": "Indeed", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$145K – $195K", "category": "Engineering",
        "description": "Build the iOS app used by millions of riders.",
        "required_skills": ["swift", "ios", "xcode", "rest", "git"],
        "preferred_skills": ["react native", "objective-c", "firebase"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 9, "title": "Android Developer", "company": "Uber",
        "source": "Monster", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$140K – $190K", "category": "Engineering",
        "description": "Develop features for the Uber Android app at massive scale.",
        "required_skills": ["kotlin", "android", "android studio", "java", "rest"],
        "preferred_skills": ["kotlin coroutines", "jetpack compose", "git"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 10, "title": "Staff Software Engineer", "company": "Meta",
        "source": "LinkedIn", "location": "Menlo Park, CA", "job_type": "Full-time",
        "salary_range": "$220K – $350K", "category": "Engineering",
        "description": "Lead technical direction for key infrastructure projects.",
        "required_skills": ["python", "c++", "java", "distributed systems", "sql", "leadership"],
        "preferred_skills": ["rust", "scala", "spark", "kafka"],
        "experience_years_min": 10, "experience_years_max": 20,
        "education_required": "master",
    },
    {
        "id": 11, "title": "Frontend Engineer (React)", "company": "Figma",
        "source": "ZipRecruiter", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$155K – $205K", "category": "Engineering",
        "description": "Push the limits of what's possible in browser-based design tools.",
        "required_skills": ["react", "typescript", "javascript", "css", "html"],
        "preferred_skills": ["webgl", "wasm", "performance optimisation", "webpack"],
        "experience_years_min": 4, "experience_years_max": 9,
        "education_required": "bachelor",
    },
    {
        "id": 12, "title": "Platform Engineer", "company": "Shopify",
        "source": "Glassdoor", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$140K – $180K", "category": "Engineering",
        "description": "Build the platform powering millions of merchants worldwide.",
        "required_skills": ["ruby", "rails", "mysql", "redis", "kubernetes", "docker"],
        "preferred_skills": ["go", "kafka", "aws", "ci/cd"],
        "experience_years_min": 4, "experience_years_max": 9,
        "education_required": "bachelor",
    },
    {
        "id": 13, "title": "Cybersecurity Engineer", "company": "Palo Alto Networks",
        "source": "Indeed", "location": "Santa Clara, CA", "job_type": "Full-time",
        "salary_range": "$160K – $220K", "category": "Engineering",
        "description": "Build security tools and systems to protect enterprise customers.",
        "required_skills": ["cybersecurity", "python", "linux", "firewalls", "ssl", "iam"],
        "preferred_skills": ["siem", "penetration testing", "tls", "aws", "soc"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "bachelor",
    },
    {
        "id": 14, "title": "Embedded Systems Engineer", "company": "Tesla",
        "source": "LinkedIn", "location": "Austin, TX", "job_type": "Full-time",
        "salary_range": "$150K – $200K", "category": "Engineering",
        "description": "Develop firmware and embedded software for Tesla vehicles.",
        "required_skills": ["c++", "c#", "linux", "python", "embedded systems", "git"],
        "preferred_skills": ["rust", "real-time systems", "can bus", "bash"],
        "experience_years_min": 4, "experience_years_max": 10,
        "education_required": "bachelor",
    },
    {
        "id": 15, "title": "Backend Engineer – Go", "company": "Cloudflare",
        "source": "Monster", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$145K – $190K", "category": "Engineering",
        "description": "Build high-performance network services at global scale.",
        "required_skills": ["go", "golang", "linux", "networking", "rest", "sql"],
        "preferred_skills": ["kubernetes", "docker", "rust", "c++"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },

    # ─── DATA SCIENCE & ML ───────────────────────────────────────────────────
    {
        "id": 16, "title": "Senior Data Scientist", "company": "Spotify",
        "source": "LinkedIn", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$160K – $210K", "category": "Data Science",
        "description": "Drive recommendations and personalisation with ML models.",
        "required_skills": ["python", "machine learning", "sql", "statistics", "pandas", "scikit-learn"],
        "preferred_skills": ["spark", "tensorflow", "a/b testing", "airflow"],
        "experience_years_min": 5, "experience_years_max": 10,
        "education_required": "master",
    },
    {
        "id": 17, "title": "Machine Learning Engineer", "company": "OpenAI",
        "source": "Glassdoor", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$200K – $350K", "category": "Data Science",
        "description": "Train and deploy large-scale language models.",
        "required_skills": ["python", "pytorch", "deep learning", "machine learning", "nlp", "tensorflow"],
        "preferred_skills": ["cuda", "distributed training", "kubernetes", "aws"],
        "experience_years_min": 5, "experience_years_max": 15,
        "education_required": "phd",
    },
    {
        "id": 18, "title": "Data Analyst", "company": "DoorDash",
        "source": "Indeed", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$95K – $130K", "category": "Data Science",
        "description": "Translate complex data into actionable business insights.",
        "required_skills": ["sql", "python", "excel", "data analysis", "statistics", "tableau"],
        "preferred_skills": ["r", "looker", "a/b testing", "pandas"],
        "experience_years_min": 2, "experience_years_max": 5,
        "education_required": "bachelor",
    },
    {
        "id": 19, "title": "Data Engineer", "company": "Snowflake",
        "source": "ZipRecruiter", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$145K – $195K", "category": "Data Science",
        "description": "Build scalable data pipelines powering analytics at scale.",
        "required_skills": ["python", "sql", "spark", "kafka", "airflow", "etl"],
        "preferred_skills": ["snowflake", "dbt", "aws", "scala", "data warehouse"],
        "experience_years_min": 4, "experience_years_max": 9,
        "education_required": "bachelor",
    },
    {
        "id": 20, "title": "AI Research Scientist", "company": "DeepMind",
        "source": "LinkedIn", "location": "London, UK", "job_type": "Full-time",
        "salary_range": "$200K – $400K", "category": "Data Science",
        "description": "Conduct cutting-edge AI research advancing the field.",
        "required_skills": ["python", "pytorch", "tensorflow", "deep learning", "machine learning", "statistics"],
        "preferred_skills": ["reinforcement learning", "computer vision", "nlp", "mathematics"],
        "experience_years_min": 5, "experience_years_max": 20,
        "education_required": "phd",
    },
    {
        "id": 21, "title": "Business Intelligence Analyst", "company": "Target",
        "source": "Monster", "location": "Minneapolis, MN", "job_type": "Full-time",
        "salary_range": "$85K – $115K", "category": "Data Science",
        "description": "Build dashboards and reports to drive retail decisions.",
        "required_skills": ["sql", "tableau", "power bi", "excel", "data analysis"],
        "preferred_skills": ["python", "r", "looker", "statistics"],
        "experience_years_min": 2, "experience_years_max": 6,
        "education_required": "bachelor",
    },
    {
        "id": 22, "title": "Computer Vision Engineer", "company": "NVIDIA",
        "source": "Glassdoor", "location": "Santa Clara, CA", "job_type": "Full-time",
        "salary_range": "$190K – $280K", "category": "Data Science",
        "description": "Build real-time computer vision systems for autonomous vehicles.",
        "required_skills": ["python", "pytorch", "computer vision", "deep learning", "c++", "tensorflow"],
        "preferred_skills": ["cuda", "opencv", "slam", "ros"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "master",
    },
    {
        "id": 23, "title": "NLP Engineer", "company": "Amazon",
        "source": "Indeed", "location": "Seattle, WA", "job_type": "Full-time",
        "salary_range": "$170K – $230K", "category": "Data Science",
        "description": "Improve Alexa and other NLP-powered products.",
        "required_skills": ["python", "nlp", "machine learning", "deep learning", "tensorflow", "pytorch"],
        "preferred_skills": ["aws", "spark", "scala", "statistics"],
        "experience_years_min": 4, "experience_years_max": 10,
        "education_required": "master",
    },

    # ─── PRODUCT & DESIGN ────────────────────────────────────────────────────
    {
        "id": 24, "title": "Senior Product Manager", "company": "Asana",
        "source": "LinkedIn", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$170K – $230K", "category": "Product",
        "description": "Define and execute the product roadmap for our collaboration suite.",
        "required_skills": ["product management", "product roadmap", "agile", "user research", "jira"],
        "preferred_skills": ["sql", "figma", "a/b testing", "stakeholder management"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "bachelor",
    },
    {
        "id": 25, "title": "UX Designer", "company": "Adobe",
        "source": "Glassdoor", "location": "San Jose, CA", "job_type": "Full-time",
        "salary_range": "$120K – $165K", "category": "Product",
        "description": "Create beautiful and intuitive experiences for creative tools.",
        "required_skills": ["ux", "figma", "wireframing", "prototyping", "user research"],
        "preferred_skills": ["sketch", "adobe xd", "invision", "ui"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 26, "title": "Product Designer", "company": "Canva",
        "source": "ZipRecruiter", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$130K – $175K", "category": "Product",
        "description": "Shape the design experience used by 150M+ creators.",
        "required_skills": ["figma", "ui", "ux", "prototyping", "user research", "wireframing"],
        "preferred_skills": ["motion design", "html", "css", "user stories"],
        "experience_years_min": 4, "experience_years_max": 9,
        "education_required": "bachelor",
    },
    {
        "id": 27, "title": "Associate Product Manager", "company": "LinkedIn",
        "source": "Indeed", "location": "Sunnyvale, CA", "job_type": "Full-time",
        "salary_range": "$110K – $150K", "category": "Product",
        "description": "Gain PM experience across LinkedIn's core platform.",
        "required_skills": ["product management", "agile", "user stories", "communication"],
        "preferred_skills": ["sql", "figma", "jira", "scrum"],
        "experience_years_min": 1, "experience_years_max": 4,
        "education_required": "bachelor",
    },
    {
        "id": 28, "title": "Scrum Master", "company": "IBM",
        "source": "Monster", "location": "Austin, TX", "job_type": "Full-time",
        "salary_range": "$100K – $140K", "category": "Product",
        "description": "Coach agile teams and remove impediments to delivery.",
        "required_skills": ["scrum", "agile", "kanban", "jira", "confluence", "stakeholder management"],
        "preferred_skills": ["project management", "leadership", "communication"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },

    # ─── MARKETING & SALES ───────────────────────────────────────────────────
    {
        "id": 29, "title": "Digital Marketing Manager", "company": "HubSpot",
        "source": "LinkedIn", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$100K – $135K", "category": "Marketing",
        "description": "Lead digital campaigns that drive pipeline and brand awareness.",
        "required_skills": ["seo", "google analytics", "google ads", "content marketing", "hubspot", "email marketing"],
        "preferred_skills": ["sem", "facebook ads", "marketo", "crm", "a/b testing"],
        "experience_years_min": 4, "experience_years_max": 9,
        "education_required": "bachelor",
    },
    {
        "id": 30, "title": "SEO Specialist", "company": "Moz",
        "source": "Indeed", "location": "Seattle, WA", "job_type": "Full-time",
        "salary_range": "$70K – $100K", "category": "Marketing",
        "description": "Grow organic search traffic through technical and content SEO.",
        "required_skills": ["seo", "google analytics", "content marketing", "html", "communication"],
        "preferred_skills": ["python", "sql", "sem", "wordpress"],
        "experience_years_min": 2, "experience_years_max": 6,
        "education_required": "bachelor",
    },
    {
        "id": 31, "title": "Content Marketing Manager", "company": "Mailchimp",
        "source": "Glassdoor", "location": "Atlanta, GA", "job_type": "Full-time",
        "salary_range": "$85K – $115K", "category": "Marketing",
        "description": "Create compelling content that educates and converts audiences.",
        "required_skills": ["content marketing", "seo", "email marketing", "social media", "communication"],
        "preferred_skills": ["hubspot", "wordpress", "google analytics", "mailchimp"],
        "experience_years_min": 3, "experience_years_max": 7,
        "education_required": "bachelor",
    },
    {
        "id": 32, "title": "Account Executive", "company": "Salesforce",
        "source": "ZipRecruiter", "location": "Chicago, IL", "job_type": "Full-time",
        "salary_range": "$90K – $180K", "category": "Sales",
        "description": "Drive enterprise software sales and close complex deals.",
        "required_skills": ["salesforce", "crm", "negotiation", "communication", "presentation"],
        "preferred_skills": ["stakeholder management", "financial modeling", "strategic planning"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 33, "title": "Growth Marketing Analyst", "company": "Duolingo",
        "source": "Monster", "location": "Pittsburgh, PA", "job_type": "Full-time",
        "salary_range": "$90K – $125K", "category": "Marketing",
        "description": "Use data to scale user acquisition and retention campaigns.",
        "required_skills": ["google analytics", "sql", "a/b testing", "growth hacking", "python"],
        "preferred_skills": ["facebook ads", "google ads", "statistics", "tableau"],
        "experience_years_min": 2, "experience_years_max": 6,
        "education_required": "bachelor",
    },
    {
        "id": 34, "title": "Social Media Manager", "company": "Twitter/X",
        "source": "LinkedIn", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$75K – $100K", "category": "Marketing",
        "description": "Manage brand presence and community engagement on social platforms.",
        "required_skills": ["social media", "content marketing", "communication", "presentation"],
        "preferred_skills": ["google analytics", "hubspot", "seo", "email marketing"],
        "experience_years_min": 2, "experience_years_max": 6,
        "education_required": "bachelor",
    },
    {
        "id": 35, "title": "Sales Development Representative", "company": "Zendesk",
        "source": "Indeed", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$60K – $90K", "category": "Sales",
        "description": "Generate qualified pipeline through outbound prospecting.",
        "required_skills": ["salesforce", "crm", "communication", "negotiation"],
        "preferred_skills": ["hubspot", "email marketing", "presentation"],
        "experience_years_min": 0, "experience_years_max": 3,
        "education_required": "bachelor",
    },
    {
        "id": 36, "title": "Product Marketing Manager", "company": "Twilio",
        "source": "Glassdoor", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$125K – $165K", "category": "Marketing",
        "description": "Drive go-to-market strategy for developer-facing products.",
        "required_skills": ["content marketing", "communication", "product management", "strategic planning", "presentation"],
        "preferred_skills": ["seo", "google analytics", "sql", "figma"],
        "experience_years_min": 4, "experience_years_max": 9,
        "education_required": "bachelor",
    },

    # ─── FINANCE & ACCOUNTING ────────────────────────────────────────────────
    {
        "id": 37, "title": "Financial Analyst", "company": "Goldman Sachs",
        "source": "LinkedIn", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$110K – $160K", "category": "Finance",
        "description": "Perform financial modelling and valuation for investment decisions.",
        "required_skills": ["financial modeling", "financial analysis", "excel", "valuation", "dcf"],
        "preferred_skills": ["python", "bloomberg terminal", "sql", "powerpoint"],
        "experience_years_min": 2, "experience_years_max": 6,
        "education_required": "bachelor",
    },
    {
        "id": 38, "title": "Investment Banking Analyst", "company": "JP Morgan",
        "source": "Monster", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$100K – $150K", "category": "Finance",
        "description": "Support M&A, IPO, and capital markets transactions.",
        "required_skills": ["investment banking", "financial modeling", "dcf", "valuation", "excel"],
        "preferred_skills": ["bloomberg terminal", "sql", "python", "presentation"],
        "experience_years_min": 0, "experience_years_max": 3,
        "education_required": "bachelor",
    },
    {
        "id": 39, "title": "Senior Accountant", "company": "Deloitte",
        "source": "Indeed", "location": "Chicago, IL", "job_type": "Full-time",
        "salary_range": "$80K – $110K", "category": "Finance",
        "description": "Manage financial statements, audits, and compliance reporting.",
        "required_skills": ["accounting", "gaap", "excel", "financial analysis", "quickbooks"],
        "preferred_skills": ["sap", "erp", "sql", "ifrs"],
        "experience_years_min": 3, "experience_years_max": 7,
        "education_required": "bachelor",
    },
    {
        "id": 40, "title": "Private Equity Associate", "company": "KKR",
        "source": "Glassdoor", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$150K – $250K", "category": "Finance",
        "description": "Source and evaluate private equity investment opportunities.",
        "required_skills": ["private equity", "financial modeling", "valuation", "dcf", "excel"],
        "preferred_skills": ["bloomberg terminal", "investment banking", "sql", "python"],
        "experience_years_min": 2, "experience_years_max": 5,
        "education_required": "bachelor",
    },
    {
        "id": 41, "title": "Data Analyst – Finance", "company": "BlackRock",
        "source": "ZipRecruiter", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$95K – $135K", "category": "Finance",
        "description": "Analyse financial datasets to guide investment strategies.",
        "required_skills": ["python", "sql", "excel", "financial analysis", "data analysis", "statistics"],
        "preferred_skills": ["r", "tableau", "bloomberg terminal", "power bi"],
        "experience_years_min": 2, "experience_years_max": 6,
        "education_required": "bachelor",
    },
    {
        "id": 42, "title": "Risk Analyst", "company": "Citibank",
        "source": "LinkedIn", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$90K – $130K", "category": "Finance",
        "description": "Identify and quantify credit, market, and operational risks.",
        "required_skills": ["financial analysis", "excel", "statistics", "sql", "accounting"],
        "preferred_skills": ["python", "bloomberg terminal", "sas", "r"],
        "experience_years_min": 2, "experience_years_max": 7,
        "education_required": "bachelor",
    },

    # ─── HEALTHCARE ──────────────────────────────────────────────────────────
    {
        "id": 43, "title": "Registered Nurse – ICU", "company": "UCSF Medical Center",
        "source": "Indeed", "location": "San Francisco, CA", "job_type": "Full-time",
        "salary_range": "$110K – $145K", "category": "Healthcare",
        "description": "Provide critical care nursing in a Level I trauma center.",
        "required_skills": ["nursing", "patient care", "critical care", "communication"],
        "preferred_skills": ["icu", "acls", "bls", "electronic health records"],
        "experience_years_min": 2, "experience_years_max": 10,
        "education_required": "bachelor",
    },
    {
        "id": 44, "title": "Healthcare Data Analyst", "company": "Epic Systems",
        "source": "Monster", "location": "Verona, WI", "job_type": "Full-time",
        "salary_range": "$80K – $115K", "category": "Healthcare",
        "description": "Analyse healthcare data to improve patient outcomes.",
        "required_skills": ["sql", "excel", "data analysis", "statistics", "python"],
        "preferred_skills": ["tableau", "r", "healthcare", "hl7"],
        "experience_years_min": 2, "experience_years_max": 7,
        "education_required": "bachelor",
    },
    {
        "id": 45, "title": "Physician – Internal Medicine", "company": "Mayo Clinic",
        "source": "LinkedIn", "location": "Rochester, MN", "job_type": "Full-time",
        "salary_range": "$220K – $300K", "category": "Healthcare",
        "description": "Provide comprehensive internal medicine care to adult patients.",
        "required_skills": ["patient care", "communication", "leadership"],
        "preferred_skills": ["electronic health records", "research"],
        "experience_years_min": 3, "experience_years_max": 30,
        "education_required": "phd",
    },
    {
        "id": 46, "title": "Clinical Research Coordinator", "company": "Pfizer",
        "source": "Glassdoor", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$65K – $90K", "category": "Healthcare",
        "description": "Coordinate clinical trials and ensure regulatory compliance.",
        "required_skills": ["communication", "data analysis", "excel", "project management"],
        "preferred_skills": ["statistics", "r", "python", "research"],
        "experience_years_min": 1, "experience_years_max": 5,
        "education_required": "bachelor",
    },

    # ─── PROJECT MANAGEMENT ──────────────────────────────────────────────────
    {
        "id": 47, "title": "Senior Project Manager", "company": "Accenture",
        "source": "ZipRecruiter", "location": "Chicago, IL", "job_type": "Full-time",
        "salary_range": "$120K – $160K", "category": "Project Management",
        "description": "Lead large-scale technology transformation programs.",
        "required_skills": ["project management", "agile", "leadership", "stakeholder management", "communication", "jira"],
        "preferred_skills": ["scrum", "kanban", "strategic planning", "risk management", "confluence"],
        "experience_years_min": 7, "experience_years_max": 15,
        "education_required": "bachelor",
    },
    {
        "id": 48, "title": "Technical Project Manager", "company": "Microsoft",
        "source": "Indeed", "location": "Redmond, WA", "job_type": "Full-time",
        "salary_range": "$140K – $185K", "category": "Project Management",
        "description": "Coordinate cross-functional engineering teams to ship products on time.",
        "required_skills": ["project management", "agile", "scrum", "jira", "communication", "stakeholder management"],
        "preferred_skills": ["sql", "python", "azure", "leadership", "strategic planning"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "bachelor",
    },
    {
        "id": 49, "title": "IT Program Manager", "company": "Walmart",
        "source": "Monster", "location": "Bentonville, AR", "job_type": "Full-time",
        "salary_range": "$110K – $150K", "category": "Project Management",
        "description": "Oversee IT programmes that support enterprise operations.",
        "required_skills": ["project management", "stakeholder management", "leadership", "strategic planning", "communication"],
        "preferred_skills": ["agile", "scrum", "jira", "erp", "risk management"],
        "experience_years_min": 6, "experience_years_max": 14,
        "education_required": "bachelor",
    },

    # ─── HUMAN RESOURCES ─────────────────────────────────────────────────────
    {
        "id": 50, "title": "HR Business Partner", "company": "Apple",
        "source": "LinkedIn", "location": "Cupertino, CA", "job_type": "Full-time",
        "salary_range": "$130K – $170K", "category": "Human Resources",
        "description": "Serve as a strategic HR partner to engineering leadership.",
        "required_skills": ["leadership", "communication", "stakeholder management", "strategic planning", "team management"],
        "preferred_skills": ["data analysis", "excel", "presentation", "project management"],
        "experience_years_min": 6, "experience_years_max": 14,
        "education_required": "bachelor",
    },
    {
        "id": 51, "title": "Technical Recruiter", "company": "Stripe",
        "source": "Glassdoor", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$95K – $135K", "category": "Human Resources",
        "description": "Source and close top engineering talent for a fast-growing fintech.",
        "required_skills": ["communication", "negotiation", "stakeholder management", "presentation"],
        "preferred_skills": ["technical recruiting", "linkedin", "crm", "data analysis"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 52, "title": "People Operations Manager", "company": "Zoom",
        "source": "ZipRecruiter", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$110K – $145K", "category": "Human Resources",
        "description": "Scale people operations, onboarding, and HR programmes globally.",
        "required_skills": ["team management", "leadership", "communication", "project management"],
        "preferred_skills": ["data analysis", "excel", "strategic planning", "presentation"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "bachelor",
    },

    # ─── EDUCATION & RESEARCH ────────────────────────────────────────────────
    {
        "id": 53, "title": "Research Scientist – AI", "company": "Microsoft Research",
        "source": "Indeed", "location": "Redmond, WA", "job_type": "Full-time",
        "salary_range": "$180K – $280K", "category": "Research",
        "description": "Publish and commercialise research on AI and machine learning.",
        "required_skills": ["python", "machine learning", "deep learning", "statistics", "pytorch", "tensorflow"],
        "preferred_skills": ["nlp", "computer vision", "reinforcement learning", "scala"],
        "experience_years_min": 5, "experience_years_max": 20,
        "education_required": "phd",
    },
    {
        "id": 54, "title": "Data Science Instructor", "company": "Coursera",
        "source": "Monster", "location": "Remote", "job_type": "Contract",
        "salary_range": "$80K – $120K", "category": "Education",
        "description": "Design and teach data science courses for learners worldwide.",
        "required_skills": ["data science", "python", "machine learning", "statistics", "communication", "presentation"],
        "preferred_skills": ["r", "pandas", "numpy", "sql", "teaching"],
        "experience_years_min": 4, "experience_years_max": 12,
        "education_required": "master",
    },

    # ─── OPERATIONS & LOGISTICS ──────────────────────────────────────────────
    {
        "id": 55, "title": "Operations Analyst", "company": "Amazon",
        "source": "LinkedIn", "location": "Seattle, WA", "job_type": "Full-time",
        "salary_range": "$80K – $110K", "category": "Operations",
        "description": "Analyse and improve supply chain and fulfilment operations.",
        "required_skills": ["sql", "excel", "data analysis", "python", "statistics"],
        "preferred_skills": ["tableau", "r", "power bi", "project management"],
        "experience_years_min": 2, "experience_years_max": 6,
        "education_required": "bachelor",
    },
    {
        "id": 56, "title": "Supply Chain Manager", "company": "Apple",
        "source": "Glassdoor", "location": "Cupertino, CA", "job_type": "Full-time",
        "salary_range": "$130K – $175K", "category": "Operations",
        "description": "Oversee global supply chain strategy and execution.",
        "required_skills": ["project management", "leadership", "strategic planning", "excel", "stakeholder management"],
        "preferred_skills": ["erp", "sap", "data analysis", "sql", "communication"],
        "experience_years_min": 7, "experience_years_max": 15,
        "education_required": "bachelor",
    },

    # ─── TECHNICAL WRITING / SOLUTIONS ──────────────────────────────────────
    {
        "id": 57, "title": "Technical Writer", "company": "Twilio",
        "source": "ZipRecruiter", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$95K – $130K", "category": "Technical Writing",
        "description": "Create world-class API documentation and developer guides.",
        "required_skills": ["communication", "html", "rest", "git", "presentation"],
        "preferred_skills": ["python", "javascript", "markdown", "graphql"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 58, "title": "Solutions Engineer", "company": "Datadog",
        "source": "Indeed", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$140K – $185K", "category": "Engineering",
        "description": "Help enterprise customers adopt observability and monitoring solutions.",
        "required_skills": ["python", "linux", "communication", "rest", "sql", "aws"],
        "preferred_skills": ["kubernetes", "docker", "datadog", "presentation", "prometheus"],
        "experience_years_min": 4, "experience_years_max": 9,
        "education_required": "bachelor",
    },

    # ─── EXTRA REMOTE ROLES ──────────────────────────────────────────────────
    {
        "id": 59, "title": "Remote Python Developer", "company": "Automattic",
        "source": "ZipRecruiter", "location": "Remote (Worldwide)", "job_type": "Full-time",
        "salary_range": "$100K – $150K", "category": "Engineering",
        "description": "Build open-source software that powers 40% of the internet.",
        "required_skills": ["python", "javascript", "rest", "sql", "git", "linux"],
        "preferred_skills": ["php", "wordpress", "mysql", "docker", "nodejs"],
        "experience_years_min": 3, "experience_years_max": 10,
        "education_required": "bachelor",
    },
    {
        "id": 60, "title": "Remote Data Engineer", "company": "GitLab",
        "source": "Monster", "location": "Remote (Worldwide)", "job_type": "Full-time",
        "salary_range": "$130K – $180K", "category": "Data Science",
        "description": "Build and maintain data infrastructure for a fully-remote company.",
        "required_skills": ["python", "sql", "dbt", "airflow", "etl", "snowflake", "git"],
        "preferred_skills": ["spark", "kafka", "aws", "docker", "kubernetes"],
        "experience_years_min": 4, "experience_years_max": 10,
        "education_required": "bachelor",
    },
    {
        "id": 61, "title": "Freelance UX Researcher", "company": "Toptal",
        "source": "LinkedIn", "location": "Remote", "job_type": "Contract",
        "salary_range": "$80K – $120K", "category": "Product",
        "description": "Conduct user research and usability testing for top tech companies.",
        "required_skills": ["user research", "ux", "communication", "presentation", "wireframing"],
        "preferred_skills": ["figma", "sketch", "statistics", "data analysis"],
        "experience_years_min": 3, "experience_years_max": 8,
        "education_required": "bachelor",
    },
    {
        "id": 62, "title": "Blockchain Developer", "company": "Coinbase",
        "source": "Glassdoor", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$160K – $230K", "category": "Engineering",
        "description": "Build secure and scalable blockchain products and infrastructure.",
        "required_skills": ["python", "go", "rust", "sql", "rest", "git", "linux"],
        "preferred_skills": ["ethereum", "solidity", "aws", "docker", "kubernetes"],
        "experience_years_min": 4, "experience_years_max": 10,
        "education_required": "bachelor",
    },
    {
        "id": 63, "title": "Quantitative Analyst", "company": "Two Sigma",
        "source": "Indeed", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$180K – $300K", "category": "Finance",
        "description": "Develop quantitative models for systematic trading strategies.",
        "required_skills": ["python", "r", "statistics", "machine learning", "sql", "mathematics"],
        "preferred_skills": ["scala", "spark", "financial modeling", "c++", "pandas"],
        "experience_years_min": 3, "experience_years_max": 12,
        "education_required": "phd",
    },
    {
        "id": 64, "title": "Graphic Designer", "company": "Squarespace",
        "source": "Monster", "location": "New York, NY", "job_type": "Full-time",
        "salary_range": "$70K – $100K", "category": "Design",
        "description": "Create beautiful visual assets for marketing and product.",
        "required_skills": ["figma", "ui", "css", "html", "presentation"],
        "preferred_skills": ["sketch", "adobe xd", "invision", "motion design"],
        "experience_years_min": 2, "experience_years_max": 7,
        "education_required": "bachelor",
    },
    {
        "id": 65, "title": "Infrastructure Security Engineer", "company": "Cloudflare",
        "source": "ZipRecruiter", "location": "Remote", "job_type": "Full-time",
        "salary_range": "$160K – $220K", "category": "Engineering",
        "description": "Harden and defend Cloudflare's global network infrastructure.",
        "required_skills": ["cybersecurity", "linux", "python", "networking", "firewalls", "iam"],
        "preferred_skills": ["penetration testing", "siem", "tls", "kubernetes", "go"],
        "experience_years_min": 5, "experience_years_max": 12,
        "education_required": "bachelor",
    },
]
