services:
  pulseboard-backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      CORS_ORIGIN: "*"
    restart: unless-stopped

  pulseboard-frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - pulseboard-backend
    restart: unless-stopped
