{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.ingressname }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "littledoctor.labels" . | nindent 4 }}
    component: {{ .Values.frontend.component }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressclassname }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.frontend.name }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
