{{- if .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "littledoctor.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "littledoctor.labels" . | nindent 4 }}
    component: {{ .Values.frontend.component }}
automountServiceAccountToken: {{ .Values.frontend.serviceAccount.automount }}
{{- end }}
