{{- if not .Values.cognito.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "little-doctor-academy.fullname" . }}-cognito
  labels:
    {{- include "little-doctor-academy.labels" . | nindent 4 }}
type: Opaque
stringData:
  VITE_COGNITO_USER_POOL_ID: {{ .Values.cognito.userPoolId | quote }}
  VITE_COGNITO_CLIENT_ID: {{ .Values.cognito.clientId | quote }}
  VITE_COGNITO_REGION: {{ .Values.cognito.region | quote }}
{{- end }}
