{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "little-doctor-academy.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "little-doctor-academy.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
