apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pulseboard.labels" . | nindent 4 }}
    component: {{ .Values.backend.component }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.global.appLabel }}
    component: {{ .Values.backend.component }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
