apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-end-storage
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
  - ReadWriteOnce 
  storageClassName: {{ .Values.global.storage.ClassName }} 
  resources:
    requests:
      storage: {{ .Values.global.storage.size }}
