
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.global.secrets.name }}"
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.global.secrets.ansible_secrets }}"
        objectType: "secretsmanager"
        jmesPath:
        - path: username
          objectAlias: ANSIBLE_USERNAME
        - path: password
          objectAlias: ANSIBLE_PASSWORD
      - objectName: "{{ .Values.global.secrets.smtp_secrets }}"
        objectType: "secretsmanager"
        jmesPath:
        - path: SMTP_USER 
          objectAlias: SMTP_USER
        - path: SMTP_PASS
          objectAlias: SMTP_PASS
  secretObjects:
  - secretName: ansible-secrets
    type: Opaque
    data:
    - objectName: ANSIBLE_USERNAME # This is the objectAlias defined above
      key: ANSIBLE_USERNAME # This is the key in the Kubernetes secret
    - objectName: ANSIBLE_PASSWORD
      key: ANSIBLE_PASSWORD
  - secretName: smtp-secrets
    type: Opaque
    data:
    - objectName: SMTP_USER
      key: SMTP_USER
    - objectName: SMTP_PASS
      key: SMTP_PASS
